evento/appweb/urls.py
from django.conf.urls import url,include
from django.contrib import admin

from . import views

urlpatterns = [
	url(r'^$',views.index, name='login'),
	url(r'^$',views.logout, name='logout'),
	url(r'^home/$',views.home, name='home'),	
	url(r'^cadastroUsuario/$',views.cadastro_usuario, name='cadastro_usuario'),

	#urls de outras apps
	url(r'^evento/',include('core.urls', namespace='evento')),
    url(r'^inscricao/',include('inscricao.urls', namespace='inscricao')),  		
    url(r'^cupom/',include('inscricao.urls', namespace='cupom')), 
    url(r'^comum/',include('comum.urls', namespace='tag')),      
]

evento/comum/urls.py
from django.conf.urls import url
from django.contrib import admin

from . import views

urlpatterns = [	
	url(r'^tagUsuario/$',views.adicionarTagUsuario.as_view(), name='tag_usuario'),
	url(r'^(?P<pk>\d+)/tagEvento/$',views.adicionarTagEvento.as_view(), name='tag_evento'),
]

evento/config/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('appweb.urls')),    
]

evento/core/urls.py
from django.conf.urls import url
from django.contrib import admin

from . import views

urlpatterns = [	

	url(r'^cadastro_evento/$',views.CadastroEvento.as_view(), name='cadastro_evento'),
	url(r'^(?P<pk>\d+)/cadastro_atividade/$', views.CadastroAtividade.as_view(), name='cadastro_atividade'),
	url(r'^meus_eventos/$',views.MeusEventos.as_view(), name='lista_eventos'),
	url(r'^eventos/$',views.Inscrever.as_view(), name='lista_outros_eventos'),
	url(r'^(?P<pk>\d+)/$',views.EventoEspecifico.as_view(), name='evento'),
	url(r'^criar_equipe/$',views.CriarEquipe.as_view(), name='criar_equipe'),
	url(r'^(?P<pk>\d+)/associar_evento/$',views.AssociarEvento.as_view(), name='associar_evento'),

]

evento/inscricao/urls.py
from django.conf.urls import url
from django.contrib import admin

from . import views

urlpatterns = [
	url(r'^(?P<pk>\d+)/cadastrarInscricao/$',views.Inscrever.as_view(), name='inscricao'),
	url(r'^(?P<pk>\d+)/cadastroCupom/$',views.CadastroCupom.as_view(), name='cadastro_cupom'),	
]

evento/appweb/models.py
from django.db import models
# Create your models here.

evento/inscricao/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.core.validators import MaxValueValidator
# Create your models here.

class Inscricao(models.Model):	
	usuario = models.ForeignKey('auth.User', on_delete=models.CASCADE, related_name='minhas_inscricoes')	
	evento = models.ForeignKey('core.Evento', on_delete=models.CASCADE, related_name='minhas_inscricoes')
	atividades = models.ManyToManyField('core.Atividade')
	cupom = models.OneToOneField('Cupom',related_name='minha_inscricao',null=True)	

	def __str__(self):
		return self.usuario.first_name

	def validate_inscricao_repetida(self):
		for inscricao in Inscricao.objects.all():
			if self.evento == inscricao.evento and self.usuario == inscricao.usuario:
				raise ValidationError('Inscricao ja existe')	
		
	def clean(self):
		#evitar inscricoes repetidas
		super(Inscricao, self).clean()
		self.validate_inscricao_repetida()

	def save(self, *args, **kwargs):
		self.clean()
		super(Inscricao, self).save()

class Cupom(models.Model):
	nome_cupom = models.CharField(max_length=25)
	desconto = models.PositiveIntegerField(validators=[MaxValueValidator(100)])		
	data_de_inicio = models.DateTimeField(null=True)
	data_de_fim = models.DateTimeField(null=True)	

	def usar_desconto(self):
		if self.minha_inscricao != None:
			self.minha_inscricao.meu_pagamento = self.minha_inscricao.meu_pagamento * (1 - self.desconto/100)			

	def __str__(self):
		return self.nome_cupom,


class CupomAutomatico(Cupom):
	evento = models.OneToOneField('core.Evento',related_name='meus_cupons',default='')

	def descontar_valor_evento(self):
		if self.evento in EventoInscrevivel.objects.all():
			e = EventoInscrevivel.objects.get(pk = self.evento.pk)
			e.valor = e.valor * (1 - self.desconto/100)
			e.save()						
		else:
			for atividade in Atividade.objects.filter(evento=self.evento):
				atividade.valor = atividade.valor * (1 - self.desconto/100)
				atividade.save()					


class Pagamento(models.Model):	
	valor_total = models.FloatField(null=True)
	pago = models.BooleanField(default=False)	
	inscricao = models.OneToOneField('inscricao.Inscricao',related_name='meu_pagamento',default='')

	def is_pago(self):
		return self.pago
			
	#Calcular_Valor_Total atribui ao valor total, o valor de todas atividades que inscricao possui
	def calcular_valor_total(self):
		itens = self.inscricao.atividades.all()
		self.valor_total = 0
		for i in itens:
			self.valor_total += i.valor

		return self.valor_total

	def save(self, *args, **kwargs):		
		self.calcular_valor_total()
		super(Pagamento, self).save(*args, **kwargs)


from core.models import Evento,EventoInscrevivel,Atividade

evento/appweb/forms/adicionarTag.py
from django import forms
from comum.models import TagEvento,TagUsuario

class AddTagUsuario(forms.ModelForm):
	class Meta:
		model = TagUsuario
		exclude = ['usuario']
		fields = ('usuario','nome_tag')				

class AddTagEvento(forms.ModelForm):
	class Meta:
		model = TagEvento
		exclude = ['evento']			
		fields = '__all__'		

evento/appweb/forms/associarEventoForm.py
from django import forms
from core.models import Evento
from django.contrib.auth.models import User

class FormEventoPrincipal(forms.ModelForm):	
	def __init__(self, *args, **kwargs):
		self.eventos = kwargs.pop("eventos")
		super(FormEventoPrincipal, self).__init__(*args, **kwargs)	
		self.fields['evento_principal'] = forms.ChoiceField(choices=([(evento, evento) for evento in self.eventos]))
			
	class Meta:
		model = Evento	
		fields = ['evento_principal']

	

evento/appweb/forms/associcarInstituicaoForm.py
#TODO

evento/appweb/forms/cadastroAtividadeForm.py
from django import forms
from core.models import Atividade, Responsavel

class AtividadeForm(forms.ModelForm):		

	class Meta:
		model = Atividade
		exclude = ['usuario_criador', 'horario_inicio','horario_final','atividades_proibidas','local','evento','responsavel']		
		fields = '__all__'


class ResponsavelForm(forms.ModelForm):	
	class Meta:
		model = Responsavel		
		fields = '__all__'		

evento/appweb/forms/cadastroCupomForm.py
from django import forms
from inscricao.models import Cupom

class CupomForm(forms.ModelForm):
	def __init__(self, *args, **kwargs):
		self.user = kwargs.pop("user") #recebendo usuario logado
		super(CupomForm, self).__init__(*args, **kwargs)			
		self.fields['desconto'].label = 'Desconto em porcento'

	class Meta:
		model = Cupom
		exclude = ['data_de_fim','data_de_inicio','evento']		
		fields = '__all__'	

evento/appweb/forms/cadastroEventoForm.py
from django import forms
from django.forms import extras
from core.models import Evento


class EventoForm(forms.ModelForm):
	inscricao_direta = forms.BooleanField(required=False)
	
	class Meta:
		model = Evento
		exclude = ['membros','evento_principal','data_inicio','data_de_fim']
		fields = '__all__'

evento/appweb/forms/cadastroUsuarioForm.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UsuarioForm(UserCreationForm):

    class Meta:
        model = User
        fields = ("first_name","last_name","username", "password1", "password2")

evento/appweb/forms/criarEquipeForm.py
from django import forms
from django.contrib.auth.models import User
from core.models import Evento





class EquipeForm(forms.ModelForm):
	def __init__(self, arg):
		self.user = kwargs.pop("user")
		super(EquipeForm, self).__init__(*args, **kwargs)

		self.fields['membros'].queryset = auth.USER.objects.filter(first_name != self.user)
		self.fields['nome_evento'].queryset = self.Evento.objects.all()


	class Meta:
		model = Evento
		fields = ('membros','nome_evento')

evento/appweb/forms/inscricaoForm.py
import json
from django import forms
from core.models import Evento, Atividade
from inscricao.models import Inscricao

#forms.CheckboxSelectMultiple()
class InscricaoForm(forms.Form):	
	def __init__(self, *args, **kwargs):
		self.atividades = kwargs.pop("atividades")
		super(InscricaoForm, self).__init__(*args, **kwargs)			
		self.fields["atividades"] = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple,choices=([(atividade.pk, atividade) for atividade in self.atividades]))
		#self.fields["atividades"].widget = forms.CheckboxSelectMultiple()
	
	class Meta:
		model = Inscricao
		exclude = ['usuario','evento','cupom']
		fields = '__all__'

evento/appweb/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from .forms.cadastroUsuarioForm import UsuarioForm
from .forms.cadastroEventoForm import EventoForm
from .forms.cadastroAtividadeForm import AtividadeForm

# Create your views here.
def index(request):	
	if request.method == "POST":#TODO
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username=username, password=password)
		if user is not None:
			login(request, user)
			return redirect('home')
		else:
			return HttpResponse("<h1>LOGIN ERROR</h1>")

	else:		
		form = AuthenticationForm()
		return render(request, "appweb/index.html", {'form':form})

def logout(request):
	logout(request)

def home(request):
	return render(request,"appweb/home.html")

def cadastro_usuario(request):
	if request.method == "POST":
		form = UsuarioForm(request.POST)
		if form.is_valid():
			usuario = form.save(commit = False) 					
			usuario.save()
			return redirect('login')
		else:
			return HttpResponse("<h1>CADASTRO INVALIDO</h1>")
	else:
		form = UsuarioForm()
		return render(request, 'appweb/form.html', {'form': form})

	

evento/inscricao/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.views import View
from appweb.forms.inscricaoForm import InscricaoForm
from appweb.forms.cadastroCupomForm import CupomForm
from core.models import EventoInscrevivel,Evento,Atividade
from inscricao.models import Cupom,Pagamento,Inscricao

# Create your views here.
class Inscrever(View):
	form = InscricaoForm	
	def set_inscrever(self,evento,request):
		if evento.pk in [evento_inscrevivel.pk for evento_inscrevivel in EventoInscrevivel.objects.all()]:
			inscricao = evento.inscrever(request.user)				
			Pagamento(inscricao=inscricao).save()
			return redirect('evento:lista_outros_eventos')
		inscricao = evento.inscrever(request.user,request.POST.getlist('atividades'))				
		Pagamento(inscricao=inscricao).save()
						

	def post(self, request, *args, **kwargs):		
		form = self.form(data=request.POST, atividades=Atividade.objects.all())											
		evento = get_object_or_404(Evento, pk=self.kwargs["pk"])														
		if form.is_valid():
			if evento.pk in [evento_inscrevivel.pk for evento_inscrevivel in EventoInscrevivel.objects.all()]:
				evento = EventoInscrevivel.objects.get(pk=evento.pk)				
				return self.set_inscrever(evento,self.request)
			return self.set_inscrever(evento,self.request)
							
	def get(self, request, *args, **kwargs):
		evento = get_object_or_404(Evento, pk=self.kwargs["pk"])		
		form = self.form(atividades=Atividade.objects.filter(evento=evento))													
		return render(request, 'appweb/inscricaoForm.html', {'form':form})


class CadastroCupom(View):
	form = CupomForm
	def get(self, request, *args, **kwargs):		
		form = self.form(user=self.request.user)
		return render(request, 'appweb/cadastroCupom.html', {'form': form})

	def post(self, request, *args, **kwargs):	
		evento = get_object_or_404(Evento, pk=self.kwargs["pk"])		
		form = self.form(request.POST, user=self.request.user)		
		if form.is_valid():
			cupom = form.save(commit = False)
			cupom.evento = evento 								
			cupom.save()
			return redirect('evento:evento', pk=self.kwargs["pk"])	

evento/appweb/templates/appweb/ajaxForm.html
{% extends './base.html' %}
{%load bootstrap%}

{%block content%}
		{%block js%}
			<script language="javascript">		
				$(document).ready(function(){	
				    $("#id_evento").change(function(){populateAtividade()});});			       	    	
				    	eventos = {{ form.eventos | safe}};
				        atividades_por_evento = {{form.atividades_por_evento | safe}};				       	
				       	populateEventos();
						$("#id_atividade").empty();						

						function populateEventos(){				       		
				       		$("#id_evento").empty();							
							$.each(eventos, function(v){
								$("#id_evento").append($("<option></option>")
									.attr("value", eventos[v])
									.text(eventos[v]));
							});
				       	}		

				       	function populateAtividade(){								       		
							evento = $("#id_evento option:selected").text();
							$("#id_atividade").empty();
							for (let [e, eatividades] of Object.entries(atividades_por_evento)){								
								if(e == evento){																			
									for(atividade in eatividades){									
													$("#id_atividade")
														.append($("<option></option>")
						                                .attr("value", eatividades[atividade])
		                	                			.text(eatividades[atividade]));					
									}							
								}
							}
				       	}
				       									
			</script>
		{%endblock%}
		<form method="POST">{% csrf_token %}
			<div class="col-sm-10">
	        <div id='evento'>
	        	{{form|bootstrap}}
        	</div>         	
	        <button type="submit" name="go" class="btn btn-lg btn-primary btn-block">Sign up</button>
	        </div>	            
       </form>
{% endblock %}

evento/appweb/templates/appweb/associarEvento.html
{% extends './baseBootstrap.html' %}
{%load bootstrap%}
	{%block content%}
		<nav class="barra">
			<div class="nome">
				<h2>Associar Evento</h2>
			</div>			
		</nav>
		<form method="POST">{% csrf_token %}
			<div class="col-sm-12">
	        {{form_evento_principal|bootstrap}}		            	        	      
	        <button type="submit" name="go" class="btn btn-success btn-md btn-block">SALVAR</button>
	        </div>	            
       </form>
{% endblock %}

evento/appweb/templates/appweb/atividadeForm.html
{% extends './baseBootstrap.html' %}
{% load static %}
{%load bootstrap%}
<body>


	<div class="conteiner">
		{%block content%}
		<nav class="barra">
			<div class="nome">
				<h2>Cadastro de Atividade</h2>
			</div>
			
		</nav>
		<form method="POST">{% csrf_token %}
			<div class="col-sm-12">
	        {{ atividade_form|bootstrap}}
	        {{ responsavel_form|bootstrap}}

	        <button type="submit" name="go" class="btn btn-success btn-md btn-block">SALVAR</button>
       </form>
	{% endblock %}
	</div>
</body>

</html>

evento/appweb/templates/appweb/base.html
{% load static %}
<html>
<head>
	<link rel="stylesheet" type="text/css" href="{% static 'cssBootstrap/bootstrap.min.css'%}">
	<link rel="stylesheet" type="text/css" href="{% static 'cssBootstrap/bootstrap-theme.min.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'cssPersonalizado/css/basePersonalizado.css'%}">
	
	<title>Saturday Eventos</title>	
</head>
<header>
    <nav class="navbar ">
        <a class="navbar-brand " href="{% url 'home'%}">Saturday'S Events</a>
    </nav>
</header>
<body>
	<div class="container">
    	<div class="row" id="pwd-container">	
    		{% block content %}
            {% endblock %}
    	</div>
	</div>
</body>
<footer class="footer navbar-fixed-bottom ">
    <div class="container">
        <span>© 2017 Equipe Saturday Copyright</span> 
    </div>
</footer>
</html>

evento/appweb/templates/appweb/baseBootstrap.html
{% load static %}
<html>
<head>
	<link rel="stylesheet" type="text/css" href="{% static 'cssBootstrap/bootstrap.min.css'%}">
	<link rel="stylesheet" type="text/css" href="{% static 'cssBootstrap/bootstrap-theme.min.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'cssPersonalizado/css/basePersonalizado.css'%}">
	
	<title>Saturday Eventos</title>	

    <header>
    <nav class="navbar ">
        <a class="navbar-brand " href="{% url 'home'%}">Saturday'S Events</a>
    </nav>
</header>

    <footer class="footer navbar-fixed-bottom ">
    <div class="container">
        <span>© 2017 Equipe Saturday Copyright</span> 
    </div>
</footer>
</head>

<body>
	<div class="container">
    	<div class="row" id="pwd-container">	
    		{% block content %}
            {% endblock %}
    	</div>
	</div>
</body>
</html>

evento/appweb/templates/appweb/baseMaterialize.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<script src="{% static 'cssPersonalizado/js/jquery.js' %}"></script>
    <!--<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.0/jquery.js"></script>-->
    <script type="text/javascript" src="{% static 'cssMaterialize/js/materialize.js'%}"></script>
    <script type="text/javascript" src="{% static 'cssMaterialize/js/materialize.min.js'%}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'cssMaterialize/css/materialize.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'cssMaterialize/css/materialize.min.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'cssPersonalizado/css/base.css'%}">
    <script type="text/javascript" src="{% static 'cssPersonalizado/js/jsPersonalizado.js' %}"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<title>Saturday Eventos</title>
	<header>
	<nav>
	    <div class="nav-wrapper">
	      <a href="{% url 'home'%}" class="brand-logo">Saturday'S Events</a>
	      <a href="{% url 'logout' %}" class="material-icons right">exit_to_app</a>
	    </div>
  	</nav>
</header>
<footer class="page-footer">
	<div class="footer-copyright">
		<div class="container">
			© 2017 Equipe Saturday Copyright
		</div>
	</div>
</footer>
</head>
<body>
	<div class="container">
		<div class="row">
			{% block content %}
			{% endblock %}
		</div>
		
	</div>
</body>
</html>

evento/appweb/templates/appweb/cadastroAtividade.html
{% extends './base.html' %}
{%load bootstrap%}

{%block content%}
			<form method="POST">{% csrf_token %}
				<div class="col-sm-10">
		        {{ form|bootstrap}}            	           	        
		        <button type="submit" name="go" class="btn btn-lg btn-primary btn-block">Save</button>
		        </div>	           
           </form>
{% endblock %}

evento/appweb/templates/appweb/cadastroCupom.html
{% extends './baseBootstrap.html' %}
{%load bootstrap%}

{%block content%}
		<nav class="barra">
			<div class="nome">
				<h2>Cadastro de Cupom</h2>
			</div>
			
		</nav>
			<form method="POST">{% csrf_token %}
				<div class="col-sm-12">
		        {{ form|bootstrap}}            	           	        
		        <button type="submit" name="go" class="btn btn-success btn-md btn-block">SALVAR</button>
		        </div>	           
           </form>
{% endblock %}

evento/appweb/templates/appweb/criaEquipe.html
{% extends 'baseBootstrap.html' %}
{% block content %}
<form action = "" method="post">
	 {% csrf_token %}
	 {{ form.as_p}}
	 <button> adciona</button>
	 </form>
	 
{% endblock %}

evento/appweb/templates/appweb/eventos.html
{% extends './baseMaterialize.html' %}
{% block content%}
{%for evento in eventos%}

  <ul class="collapsible" data-collapsible="accordion">
    <li>
      <div class="collapsible-header"><i class="material-icons">event_available</i>Evento: {{evento}}</div>
      <div class="collapsible-body">
      	  <div class="collection">
		    <a href="{% url 'inscricao:inscricao' pk=evento.pk %}" class="collection-item">Inscrever-se nas Atividades</a>  
  			</div>
      </div>

    </li>
  </ul>
{% empty %}
<ul class="collapsible" data-collapsible="accordion">
    <li>
      <div class="collapsible-header"><i class="material-icons">event_available</i>Empty list eventos</div>
      </li>
    </ul>
    
{% endfor %}
{%endblock%}

evento/appweb/templates/appweb/form.html
{% extends './baseBootstrap.html' %}
{%load bootstrap%}

{%block content%}
		<nav class="barra">
			<div class="nome">
				<h2>Formulário de Cadastro </h2>
			</div>
			
		</nav>


			<form method="POST">{% csrf_token %}
				<div class="col-sm-12">
		        {{ form|bootstrap}}            	           	        
		        <button type="submit" name="go" class="btn btn-success btn-md btn-block">SALVAR</button>
		        </div>	            
           </form>
{% endblock %}

evento/appweb/templates/appweb/index.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <script type="text/javascript" href="{% static 'cssMaterialize/js/materialize.js'}"></script>
  <script type="text/javascript" href="{% static 'cssMaterialize/js/materialize.min.js'}"></script>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="{% static 'cssMaterialize/css/materialize.css'%}">
  <link rel="stylesheet" type="text/css" href="{% static 'cssMaterialize/css/materialize.min.css'%}">
  <link rel="stylesheet" type="text/css" href="{% static 'cssPersonalizado/css/base.css'%}">

  <title>Login</title>
</head>

<body>
  {%block content%}
    <div class="conteiner">
        <div class="row">
            <div class="col s4 offset-s4">
                <div class="card-panel teal darken-2">
                    <div class="card-content white-text center">
                        <h5>Saturday'S Events</h5>
                    </div>
                </div>
            </div>
            

            <div class="col s4 offset-s4">
                <div class="card-panel ">
                    <form method="POST">
                        {% csrf_token %}
                        {{form.as_p}}
                        <button type="submit" name="action" class="waves-effect waves-light btn">Sign in</button> 
                    </form>
                </div>
            </div>
            <div class="col s4 offset-s4">
                <div class="card-panel">
                    <span>
                        New to Saturday'S?  <a href="{% url 'cadastro_usuario'%}">Create an account.</a> 
                    </span>
                    
                </div>                
            </div>

        </div>
    </div>    
</body>
</html>

{%endblock%}

evento/appweb/templates/appweb/inscricaoForm.html
{% extends './baseBootstrap.html' %}
{%load bootstrap%}

{%block content%}
		<form method="POST">{% csrf_token %}
			<div class="col-sm-12">	       
	        	{{form|bootstrap}}     	
	        <button type="submit" name="go" class="btn btn-success btn-md btn-block">INSCREVER-SE</button>
	        </div>	            
       </form>
{% endblock %}

evento/appweb/templates/appweb/meusEventos.html
{% extends './baseMaterialize.html' %}
{% load static %}
{% block content%}
{%for evento in eventos%}
  <ul class="collapsible" data-collapsible="accordion">
    <li>
      <div class="collapsible-header"><i class="material-icons">event_available</i>Evento: {{evento}}</div>
      <div class="collapsible-body">
      	  <div class="collection">
		    <a href="{% url 'evento:cadastro_atividade' pk=evento.pk %}" class="collection-item">Adicionar Atividade</a>
		    <a href="{% url 'cupom:cadastro_cupom' pk=evento.pk %}" class="collection-item">Cadastrar Cupom</a>
		    <a href="{% url 'evento:associar_evento' pk=evento.pk %}" class="collection-item">Associar Evento</a>
		    <a href="{% url 'tag:tag_evento' pk=evento.pk %}" class="collection-item"></span>Adicionar Tag</a>
  			</div>
      </div>
    </li>
  </ul>
{% empty %}
<ul class="collapsible" data-collapsible="accordion">
    <li>
      <div class="collapsible-header"><i class="material-icons">event_available</i>Empty list eventos</div>
    
{% endfor %}
{%endblock%}